/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.outros.corp;

import com.mycompany.ferramentas.BancoDeDadosMySql;
import com.mycompany.ferramentas.Formularios;
import com.mycompany.visao.categoria.CadCategoria;
import com.mycompany.visao.categoria.ListCategoria;
import com.mycompany.visao.cidade.CadCidade;
import com.mycompany.visao.cidade.ListCidade;
import com.mycompany.visao.endereco.CadEndereco;
import com.mycompany.visao.endereco.ListEndereco;
import com.mycompany.visao.estado.CadEstado;
import com.mycompany.visao.estado.ListEstado;
import com.mycompany.visao.marca.CadMarca;
import com.mycompany.visao.marca.ListMarca;
import com.mycompany.visao.pais.CadPais;
import com.mycompany.visao.pais.ListPais;
import javax.swing.JOptionPane;

/**
 *
 * @author arthur.7923
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(MAXIMIZED_BOTH);
        
        if (!BancoDeDadosMySql.conectar()) {
            JOptionPane.showMessageDialog( null, "Não foi possivel conectar ao banco de dados. O sistema será finalizado.");
            System.exit(0);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadastroCategoria = new javax.swing.JMenuItem();
        miCadastroCidade = new javax.swing.JMenuItem();
        miCadastroEstado = new javax.swing.JMenuItem();
        miCadastroPais = new javax.swing.JMenuItem();
        miCadastroMarca = new javax.swing.JMenuItem();
        miCadastroEndereco = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miConsultaCategoria = new javax.swing.JMenuItem();
        miConsultaCidade = new javax.swing.JMenuItem();
        miConsultaEstado = new javax.swing.JMenuItem();
        miConsultaPais = new javax.swing.JMenuItem();
        miConsultaMarca = new javax.swing.JMenuItem();
        miConsultaEndereco = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        miCadastroCategoria.setText("Categoria");
        miCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroCategoria);

        miCadastroCidade.setText("Cidade");
        miCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroCidade);

        miCadastroEstado.setText("Estado");
        miCadastroEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEstadoActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroEstado);

        miCadastroPais.setText("Pais");
        miCadastroPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPaisActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroPais);

        miCadastroMarca.setText("Marca");
        miCadastroMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroMarcaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroMarca);

        miCadastroEndereco.setText("Endereco");
        miCadastroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEnderecoActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroEndereco);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        miConsultaCategoria.setText("Categoria");
        miConsultaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaCategoria);

        miConsultaCidade.setText("Cidade");
        miConsultaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCidadeActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaCidade);

        miConsultaEstado.setText("Estado");
        miConsultaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaEstadoActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaEstado);

        miConsultaPais.setText("Pais");
        miConsultaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaPaisActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaPais);

        miConsultaMarca.setText("Marca");
        miConsultaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaMarcaActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaMarca);

        miConsultaEndereco.setText("Endereco");
        miConsultaEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaEnderecoActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaEndereco);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCategoriaActionPerformed
        if(Formularios.cadCategoria == null)
            Formularios.cadCategoria = new CadCategoria();
        
        Formularios.cadCategoria.setVisible(true);
    }//GEN-LAST:event_miCadastroCategoriaActionPerformed

    private void miConsultaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCategoriaActionPerformed
        Formularios.listCategoria = new ListCategoria();
        Formularios.listCategoria.setVisible(true);
    }//GEN-LAST:event_miConsultaCategoriaActionPerformed

    private void miConsultaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaEstadoActionPerformed
        Formularios.listEstado = new ListEstado();
        Formularios.listEstado.setVisible(true);
    }//GEN-LAST:event_miConsultaEstadoActionPerformed

    private void miCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCidadeActionPerformed
        if(Formularios.cadCidade == null)
            Formularios.cadCidade = new CadCidade();
        
        Formularios.cadCidade.setVisible(true);
    }//GEN-LAST:event_miCadastroCidadeActionPerformed

    private void miCadastroEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEstadoActionPerformed
        if(Formularios.cadEstado == null)
            Formularios.cadEstado = new CadEstado();
        
        Formularios.cadEstado.setVisible(true);
    }//GEN-LAST:event_miCadastroEstadoActionPerformed

    private void miConsultaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCidadeActionPerformed
        Formularios.listCidade = new ListCidade();
        Formularios.listCidade.setVisible(true);
    }//GEN-LAST:event_miConsultaCidadeActionPerformed

    private void miCadastroPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPaisActionPerformed
        if(Formularios.cadPais == null)
            Formularios.cadPais = new CadPais();
         
         Formularios.cadPais.setVisible(true);
    }//GEN-LAST:event_miCadastroPaisActionPerformed

    private void miConsultaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaPaisActionPerformed
        Formularios.listPais = new ListPais();
        Formularios.listPais.setVisible(true);
    }//GEN-LAST:event_miConsultaPaisActionPerformed

    private void miCadastroMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroMarcaActionPerformed
        if(Formularios.cadMarca == null)
            Formularios.cadMarca = new CadMarca();
         
         Formularios.cadMarca.setVisible(true);
    }//GEN-LAST:event_miCadastroMarcaActionPerformed

    private void miCadastroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEnderecoActionPerformed
        if(Formularios.cadEndereco == null)
            Formularios.cadEndereco = new CadEndereco();
         
         Formularios.cadEndereco.setVisible(true);
    }//GEN-LAST:event_miCadastroEnderecoActionPerformed

    private void miConsultaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaMarcaActionPerformed
        Formularios.listMarca = new ListMarca();
        Formularios.listMarca.setVisible(true);
    }//GEN-LAST:event_miConsultaMarcaActionPerformed

    private void miConsultaEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaEnderecoActionPerformed
        Formularios.listEndereco = new ListEndereco();
        Formularios.listEndereco.setVisible(true);
    }//GEN-LAST:event_miConsultaEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miCadastroCategoria;
    private javax.swing.JMenuItem miCadastroCidade;
    private javax.swing.JMenuItem miCadastroEndereco;
    private javax.swing.JMenuItem miCadastroEstado;
    private javax.swing.JMenuItem miCadastroMarca;
    private javax.swing.JMenuItem miCadastroPais;
    private javax.swing.JMenuItem miConsultaCategoria;
    private javax.swing.JMenuItem miConsultaCidade;
    private javax.swing.JMenuItem miConsultaEndereco;
    private javax.swing.JMenuItem miConsultaEstado;
    private javax.swing.JMenuItem miConsultaMarca;
    private javax.swing.JMenuItem miConsultaPais;
    // End of variables declaration//GEN-END:variables
}
